from aiogram import types
from loader import dp

@dp.message_handler(text="ℹ Biz haqimizda")
async def habar(message: types.Message):
    await message.answer(
        "<b>\"M-Service\" haqida bilasizmi?</b>\n\n\"m-service\" dasturlash yo'nalishi hamda mizojlar bilan masofaviy aloqalar, kompitur dizayini va grafikasi, robototexnika, web dasturlash, pytelegrambot bo'yicha O'zbekistondagi eng zamonaviy bilimlarni asosida loyihalar ishlab chiquvchi mutaxasislarni sizning ixtiyoringizga topshirmoqda shuning bilan qisqa muddat ichida o'z o'rnini tobora topib borayotgan \"m-service xizmatlari\" hisoblanadi. Hozirgi kunda \"m-service\" tasnifida:\n\n❇️ ISTALGAN TURDAGI DASTURLAR\n\n❇️ WEB DASTURLASH (FRONT END, BACK END)\n\n❇️ C# .NET FREMWORK, PHYTON DJANGO, PHP LARAVEL, JAVA SPRINGBOOT PROEKT(LAR)\n\n❇️ GRAFIK DIZAYN\n\n❇️ TELEGRAM BOT XIZMATLARI\n\n❇️ PHOTOSHOP\n\n❇️ KURS ISHI\n\n❇️ MUSTAQIL ISH\n\n❇️ SUNIY INTELEKT MASALALARI\n\n❇️ LOYIHALASH ISHLARI \n\nKabi jahondagi eng ommabop dasturlash tillaridan yuqori darajadagi xizmatlar tashkil etilgan. \"m-service\" nafaqat dasturlash, balki dasturlashdan tashqari, offis ilovalari bilan ishlashni ham o\'z ichiga oladi. Turli xil seminarlar, qiziqarli bahslar va real loyihalar barchasi bizda!.\n\nE\'TIBORINGIZ UCHUN RAXMAT!")

    # await message.answer("<b>\"<m-service>\" haqida bilasizmi?</b>\n\n\"m-service\" dasturlash yo'nalishi hamda mizojlar bilan masofaviy aloqalar, kompitur dizayini va grafikasi, robototexnika, web dasturlash, pytelegrambot bo'yicha O'zbekistondagi eng zamonaviy bilimlarni asosida loyihalar ishlab chiquvchi mutaxasislarni sizning ixtiyoringizga toppshirmoqda shuning bilan qisqa muddat ichida o'z o'rnini tobora topib borayotgan \"m-service xizmatlari\" hisoblanadi. Hozirgi kunda \"m-service\" tasnifida:\n\n❇️  ISTALGAN TURDAGI DASTURLAR\n\n❇️  WEB DASTURLASH  (FRONT END,  BECK END)\n\n❇️  C# .NET FREMWORK, PHYTON DGANGO, PHP LARAVEL, JAVA SPRINGBOOT PROEKTLAR(KURS ISHLAR)\n\n❇️  GRAFIK DIZAYN\n\n❇️  TELEGRAM BOT HIZMATLARI\n\n❇️  PHOTOSHOP\n\n❇️  KURS ISHI \n\n❇️ MUSTAQIL ISH \n\n❇️  SUNIY INTELEKT MASALALARI\n\n \n\n❇️  LOYIHALASH ISHLARI\\n\n kabi jahondagi eng ommabop dasturlash tillaridan yuqori darajadagi xizmatlar tashkil etilgan. \"m-service\" nafaqat dasturlash, balki dasturlashdan tashqari, offis ilovalari bilan ishlashni ham o'z ichiga oladi. Turli xil seminarlar, qiziqarli bahslar va real loyihalar barchasi bizda!.\n\n E'TIBORINGIZ UCHUN RAXMAT!")
